"""
Django settings for BerSur project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
ROOT_DIR = Path(__file__).resolve().parent.parent.parent
APPS_DIR = ROOT_DIR / "BerSur"

LOGIN_URL = "/login/"

DIAS_LABORABLES = ['Lunes', 'Martes',
                   'Miércoles', 'Jueves', 'Viernes', 'Sábado']

MESES = ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio",
         "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"]

# estos ids nos sirven para consultar los eventos o crear nuevos eventos
CALENDARS_IDS = {'subibarco@gmail.com': '26874433a7ff080913f06ef6abee083044858b46387c960638f8df657d262917@group.calendar.google.com',
                 'info@dataunc.com': 'd128f6ee8041627d805b215892f7b173addbe6f541228552e649a254c567a42b@group.calendar.google.com',
                 'info@1946bar.com': '170adba71857fbfa4f5bc80dc2671f1d76d31b50f4cbcb5fba170c9eacee2c0d@group.calendar.google.com',
                 'info@agro-bar.com': 'a87a99a3e0e523dae8caf68554111672d70a2bd33a8743ad04453c046d0b6221@group.calendar.google.com'
                 }

# estas url se utilizan para renderizar los calendarios en html
CALENDARS_URLS = {'subibarco@gmail.com': 'https://calendar.google.com/calendar/embed?height=600&wkst=2&bgcolor=%23ffffff&ctz=America%2FArgentina%2FBuenos_Aires&showTitle=0&showNav=0&mode=WEEK&hl=es_419&showTabs=0&showPrint=1&showCalendars=1&src=MjY4NzQ0MzNhN2ZmMDgwOTEzZjA2ZWY2YWJlZTA4MzA0NDg1OGI0NjM4N2M5NjA2MzhmOGRmNjU3ZDI2MjkxN0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t&color=%23A79B8E',
                  'info@dataunc.com': 'https://calendar.google.com/calendar/embed?height=600&wkst=2&bgcolor=%23ffffff&ctz=America%2FArgentina%2FBuenos_Aires&showTitle=0&showNav=0&mode=WEEK&hl=es_419&showTabs=0&showPrint=1&showCalendars=1&src=ZDEyOGY2ZWU4MDQxNjI3ZDgwNWIyMTU4OTJmN2IxNzNhZGRiZTZmNTQxMjI4NTUyZTY0OWEyNTRjNTY3YTQyYkBncm91cC5jYWxlbmRhci5nb29nbGUuY29t&color=%237986CB',
                  'info@1946bar.com': 'https://calendar.google.com/calendar/embed?height=600&wkst=2&bgcolor=%23ffffff&ctz=America%2FArgentina%2FBuenos_Aires&showTitle=0&showNav=0&mode=WEEK&hl=es_419&showTabs=0&showPrint=1&showCalendars=1&src=MTcwYWRiYTcxODU3ZmJmYTRmNWJjODBkYzI2NzFmMWQ3NmQzMWI1MGY0Y2JjYjVmYmExNzBjOWVhY2VlMmMwZEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t&color=%233F51B5',
                  'info@agro-bar.com': 'https://calendar.google.com/calendar/embed?height=600&wkst=2&bgcolor=%23ffffff&ctz=America%2FArgentina%2FBuenos_Aires&showTitle=0&showNav=0&mode=WEEK&hl=es_419&showTabs=0&showPrint=1&showCalendars=1&src=YTg3YTk5YTNlMGU1MjNkYWU4Y2FmNjg1NTQxMTE2NzJkNzBhMmJkMzNhODc0M2FkMDQ0NTNjMDQ2ZDBiNjIyMUBncm91cC5jYWxlbmRhci5nb29nbGUuY29t&color=%23F09300'
                  }


GOOGLE_MAPS_API_KEY = "AIzaSyCeZVCZRyKW8ovejzvMtJtmq4He2r4M4aM"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#khp%tkg=23z_ea!1m_pnphv*58lz*7_@^0#=wh4g(yqrxrjja'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'base',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
]

AUTH_USER_MODEL = 'base.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BerSur.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [APPS_DIR / "base/Templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BerSur.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': APPS_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'es-AR'

TIME_ZONE = 'America/Buenos_Aires'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
MEDIA_URL = "/images/"

STATIC_ROOT = "/static/"

STATICFILES_DIRS = [str(APPS_DIR / "base/static")]

MEDIA_ROOT = str(APPS_DIR / "base/static/images/")


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
