# Generated by Django 4.1.1 on 2022-10-21 04:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('apellido', models.CharField(max_length=200, null=True)),
                ('mail', models.EmailField(max_length=254, null=True, unique=True)),
                ('direccion', models.TextField(max_length=200, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('fecha_nacimiento', models.DateTimeField(null=True)),
                ('dni', models.IntegerField(null=True)),
                ('es_activo', models.BooleanField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('mail', models.EmailField(max_length=300)),
                ('direccion', models.TextField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('empleado', models.ManyToManyField(to='base.empleado')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('mail', models.EmailField(max_length=300)),
                ('telefono', models.CharField(max_length=300)),
                ('direccion', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Ropa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=300)),
                ('talle', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sueldo_Semanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabajadas', models.FloatField(max_length=300)),
                ('bono', models.FloatField(max_length=300)),
                ('semana', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.empleado')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.local')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tipo_pago')),
            ],
        ),
        migrations.CreateModel(
            name='Retiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('monto', models.FloatField(max_length=300)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.empleado')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.local')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(max_length=300)),
                ('precio_costo', models.FloatField(max_length=300)),
                ('precio_venta', models.FloatField(max_length=300)),
                ('precio_mayoreo', models.FloatField(max_length=300)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.local')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pago_Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.local')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='local',
            name='proveedor',
            field=models.ManyToManyField(to='base.proveedor'),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=300)),
                ('semana', models.CharField(max_length=300)),
                ('mes', models.CharField(max_length=300)),
                ('horario_ingreso', models.DateTimeField()),
                ('horario_salida', models.DateTimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('monto', models.FloatField(max_length=300)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.local')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tipo_especialidad'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ropa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tipo_ropa'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Caja_Chica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_semanal', models.FloatField(max_length=300)),
                ('semana', models.DateTimeField(max_length=300)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.local')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.rol'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
