# Generated by Django 4.1.1 on 2022-11-01 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_retiros_cancelado_delete_gastos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago_proveedor',
            name='descripcion',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago_proveedor',
            name='tipo_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.tipo_pago'),
            preserve_default=False,
        ),
    ]
