# Generated by Django 4.1.1 on 2022-11-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pago_proveedor_descripcion_pago_proveedor_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='ubicacion',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
