# Generated by Django 4.1.1 on 2022-11-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_local_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='logo',
            field=models.ImageField(default='bersurlogo.png', null=True, upload_to=''),
        ),
    ]
