# Generated by Django 4.1.1 on 2022-11-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_sueldo_semanal_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sueldo_por_hora',
            field=models.FloatField(default=0.0, max_length=300),
            preserve_default=False,
        ),
    ]
