# Generated by Django 4.1.1 on 2022-11-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_horariodetrabajo_alter_sueldo_semanal_bono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('horario_ingreso', models.DateTimeField()),
                ('horario_salida', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sueldo_semanal',
            name='horas_trabajadas',
        ),
        migrations.AddField(
            model_name='sueldo_semanal',
            name='jornadas_laborales',
            field=models.ManyToManyField(to='base.jornadalaboral'),
        ),
    ]
