# Generated by Django 4.1.1 on 2022-11-17 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_jornadalaboral_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariodetrabajo',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='jornadalaboral',
            name='fecha',
        ),
    ]
