# Generated by Django 4.1.1 on 2022-11-17 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_horariodetrabajo_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sueldo_semanal',
            name='tipo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tipo_pago'),
        ),
    ]
