# Generated by Django 4.1.1 on 2022-11-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_sueldo_semanal_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sueldo_semanal',
            name='bono',
            field=models.FloatField(default=0, max_length=300),
        ),
    ]
