# Generated by Django 4.1.1 on 2022-11-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_retiros_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiros',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
