# Generated by Django 4.1.1 on 2022-11-22 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_retiros_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodetrabajo',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.local'),
            preserve_default=False,
        ),
    ]
