# Generated by Django 4.1.1 on 2022-11-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_local_nombre_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.local'),
        ),
    ]
