# Generated by Django 4.1.1 on 2022-11-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_producto_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='empleado',
            field=models.ManyToManyField(null=True, to='base.empleado'),
        ),
        migrations.AlterField(
            model_name='local',
            name='proveedor',
            field=models.ManyToManyField(null=True, to='base.proveedor'),
        ),
    ]
