# Generated by Django 4.1.1 on 2022-11-29 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_local_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
